# see https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments
# for the detail
os: linux
dist: bionic
language: go
sudo: true

go:
  - 1.13.x

env:
  global:
    - GO111MODULE=on

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats iputils-ping

install:
  - go get -u golang.org/x/lint/golint

before_script:
  - go vet ./...
  - golint ./... | xargs -r false

script:
  - go test -v
  - go build
  - bats tests/acceptanceIPv4.bats
  - bats tests/acceptanceIPv6.bats
  - bats tests/acceptanceIPv4v6.bats

deploy:
  provider: script
  edge: true
  api_key:
    secure: "$GITHUB_TOKEN"
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
  cleanup: false
